apiVersion: apps/v1
kind: Deployment
metadata:
  name: java-backend
spec:
  replicas: 1
  selector:
     matchLabels:
       app: java
  template:
    metadata:
      labels:
        app: java
    spec:

      containers:
      - name: java-app
        image: ssbpoc.azurecr.io/java_backend:#{Build.BuildId}#
        imagePullPolicy: Always
        ports:
        - containerPort: 9090
        

---
apiVersion: v1
kind: Service
metadata:
  name: java-backend-public-exposure
spec:
  selector:
    app: java
  ports:
    - protocol: TCP
      port: 9090
      targetPort: 9090
  type: LoadBalancer
