apiVersion: apps/v1
kind: Deployment
metadata:
  name: react-frontend
spec:
  replicas: 2
  selector:
     matchLabels:
       app: react
  template:
    metadata:
      labels:
        app: react
    spec:

      containers:
      - name: react-app
        image: ssbpoc.azurecr.io/react_backend:#{Build.BuildId}#
        imagePullPolicy: Always
        ports:
        - containerPort: 3000
        

---
apiVersion: v1
kind: Service
metadata:
  name: react-frontend-public-exposure
spec:
  selector:
    app: react
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
  type: LoadBalancer
